Repository openshift-kni/eco-ci-cd, pull requests merged in 2025-09, with the labels that each got.

#190 compute: fix running unittest
  playbooks/compute/deploy-nto-gotest.yml
Labels: lgtm, approved

#188 ## adding plugin filter `reportsmerger` + tests
  playbooks/infra/reporting/roles/junit2json/doc/reportsmerger.md
  playbooks/infra/reporting/roles/junit2json/filter_plugins/reportsmerger.py
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_empty_result.json
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_input1.json
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_input2.json
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_invalid.not_json
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_missing_test_suites.json
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_mixed_result.json
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_mixed_valid.json
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_multi_result.json
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_none_input.json
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_none_result.json
  playbooks/infra/reporting/roles/junit2json/tests/unit/data/test_reportsmerger_single_result.json
  playbooks/infra/reporting/roles/junit2json/tests/unit/test_reportsmerger.py
Labels: lgtm, approved

#192 Move python requirements to file
  Containerfile
  pip.txt
Labels: lgtm, approved

#198 Compute: delete only basename folder
  playbooks/compute/deploy-nto-gotest.yml
Labels: lgtm, approved

#201 compute: fix gotest directory
  playbooks/compute/deploy-nto-gotest.yml
Labels: lgtm, approved

#202 compute: fixing dir issues
  playbooks/compute/deploy-nto-gotest.yml
Labels: approved

#205 Fix gotest sctript
  README.md
  playbooks/compute/deploy-nto-gotest.yml
Labels: lgtm, approved

#204 test pr
  README.md
Labels: do-not-merge/hold

#207 Compute: fix filter for prow
  playbooks/compute/deploy-nto-gotest.yml
Labels: lgtm, approved

#210 Remove backslashes from vm bastion deployment
  playbooks/infra/deploy-vm-bastion-libvirt.yml
Labels: lgtm

#194 Adding role `report_metadata_gen`
  playbooks/roles/report_metadata_gen/README.md
  playbooks/roles/report_metadata_gen/defaults/main.yml
  playbooks/roles/report_metadata_gen/meta/argument_specs.yml
  playbooks/roles/report_metadata_gen/meta/main.yml
  playbooks/roles/report_metadata_gen/tasks/ci-detect.yml
  playbooks/roles/report_metadata_gen/tasks/ci-metadata/dci.yml
  playbooks/roles/report_metadata_gen/tasks/ci-metadata/jenkins.yml
  playbooks/roles/report_metadata_gen/tasks/ci-metadata/unknown.yml
  playbooks/roles/report_metadata_gen/tasks/empty.yml
  playbooks/roles/report_metadata_gen/tasks/env2vars-populate.yml
  playbooks/roles/report_metadata_gen/tasks/main.yml
  playbooks/roles/report_metadata_gen/tasks/metadata-check.yml
  playbooks/roles/report_metadata_gen/templates/env2vars.j2
  playbooks/roles/report_metadata_gen/vars/env2vars/dci.yml
  playbooks/roles/report_metadata_gen/vars/env2vars/example.yml
  playbooks/roles/report_metadata_gen/vars/env2vars/jenkins.yml
Labels: lgtm, approved

#212 deploy-vm-bastion-libvirt: added skopeo and oc-mirror
  playbooks/infra/deploy-vm-bastion-libvirt.yml
Labels: lgtm, approved

#215 ## Update filter `junit2obj` rm unused import
  playbooks/roles/junit2json/filter_plugins/junit2obj.py
Labels: lgtm, approved

#216 ocp_operator_mirror: added new role
  playbooks/deploy-ocp-operators.yml
  playbooks/roles/ocp_operator_mirror/README.md
  playbooks/roles/ocp_operator_mirror/defaults/main.yaml
  playbooks/roles/ocp_operator_mirror/handlers/main.yaml
  playbooks/roles/ocp_operator_mirror/meta/main.yml
  playbooks/roles/ocp_operator_mirror/tasks/main.yaml
  playbooks/roles/ocp_operator_mirror/tasks/mirror_operator_registry_image.yaml
  playbooks/roles/ocp_operator_mirror/tasks/mirror_operators_prod.yaml
  playbooks/roles/ocp_operator_mirror/tasks/reset_registry_storage.yaml
  playbooks/roles/ocp_operator_mirror/tasks/set_auth.yaml
  playbooks/roles/ocp_operator_mirror/vars/main.yaml
Labels: lgtm, approved

#217 ocp_operator_mirror: added art operators support
  playbooks/deploy-ocp-operators.yml
  playbooks/roles/ocp_operator_mirror/README.md
  playbooks/roles/ocp_operator_mirror/defaults/main.yaml
  playbooks/roles/ocp_operator_mirror/tasks/main.yaml
  playbooks/roles/ocp_operator_mirror/tasks/mirror_art_from_fbc.yaml
  playbooks/roles/ocp_operator_mirror/tasks/mirror_operators_art.yaml
  playbooks/roles/ocp_operator_mirror/tasks/mirror_operators_prod.yaml
  playbooks/roles/ocp_operator_mirror/vars/main.yaml
Labels: lgtm

#222 Telco Compute NTO testing
  playbooks/compute/deploy-nto-gotest.yml
Labels: lgtm, approved
