Repository openshift-kni/eco-ci-cd, pull requests merged in 2025-03, with the labels that each got.

#48 Fix instructions
  playbooks/infra/deploy-bm-hypervisor.yml
Labels: lgtm, approved

#53 containerfile: added netaddr package
  Containerfile
Labels: lgtm, approved

#54 Fix file name, fix documentation
  playbooks/deploy-ocp-operators.yml
  playbooks/infra/deploy-vm-bastion-libvirt.yml
Labels: lgtm, approved

#55 bump: redhatci.ocp package to 2.0.1741806017
  requirements.yml
Labels: approved

#56 Add CA certificate update
  playbooks/infra/deploy-bm-hypervisor.yml
Labels: lgtm

#59 deploy-vm-bastion-libvirt: fix ssh key issue
  playbooks/infra/deploy-vm-bastion-libvirt.yml
Labels: lgtm, approved

#61 added playbook deploy-cnf-config.yaml
  playbooks/deploy-cnf-config.yaml
  playbooks/tasks/wait_for_mcp.yaml
  playbooks/templates/mc_add_ip.j2
  playbooks/templates/mc_fec_wa.j2
  playbooks/templates/mc_rename_nic.j2
  playbooks/templates/sctp_load_mc.j2
  playbooks/templates/worker_cnf_machine_config_pool.j2
  playbooks/templates/xt-u32-load-module.j2
Labels: lgtm, approved

#62 cnf: move deploy-cnf-config to cnf directory
  playbooks/cnf/deploy-cnf-config.yaml
  playbooks/cnf/tasks/wait_for_mcp.yaml
  playbooks/cnf/templates/mc_add_ip.j2
  playbooks/cnf/templates/mc_fec_wa.j2
  playbooks/cnf/templates/mc_rename_nic.j2
  playbooks/cnf/templates/sctp_load_mc.j2
  playbooks/cnf/templates/worker_cnf_machine_config_pool.j2
  playbooks/cnf/templates/xt-u32-load-module.j2
Labels: lgtm, approved

#64 Add eifrach as owner
  OWNERS
Labels: lgtm, approved

#65 Update repo documentation
  CONTRIBUTING.md
  README.md
Labels: lgtm, approved

#66 Add SSL certificate for bastion setup
  playbooks/infra/deploy-bm-hypervisor.yml
  playbooks/infra/deploy-vm-bastion-libvirt.yml
Labels: lgtm, approved

#67 added switch-config.yaml playbook
  inventories/cnf/switch-config.yaml
  playbooks/cnf/switch-config.yaml
  playbooks/cnf/templates/ssh_jump/ssh_config.j2
  playbooks/cnf/templates/switch/junos_configure_external_port.j2
  playbooks/cnf/templates/switch/junos_configure_secondary_port.j2
  playbooks/cnf/templates/switch/junos_configure_vlan.j2
  playbooks/cnf/templates/switch/junos_reset_port.j2
  requirements.yml
Labels: lgtm, approved

#68 Containerfile: add paramiko lib
  Containerfile
Labels: approved

#69 switch-config: formatting fix, remove extra space
  playbooks/cnf/switch-config.yaml
Labels: approved

#70 Fixed docs for deploy-ocp-operators playbook
  playbooks/deploy-ocp-operators.yml
Labels: lgtm, approved

#72 Fixed roles usage
  playbooks/deploy-ocp-operators.yml
Labels: lgtm, approved

#73 Add become on CA update block
  playbooks/infra/deploy-bm-hypervisor.yml
  playbooks/infra/deploy-vm-bastion-libvirt.yml
Labels: lgtm, approved

#74 switch: added support of multiple keys
  playbooks/cnf/switch-config.yaml
Labels: approved

#75 Containerfile: added new lib ncclient
  Containerfile
Labels: approved

#76 Fix user for helix37 in inventory
  inventory
Labels: lgtm, approved

#63 fix issue where the create VM fails due to missing line break on bash…
  playbooks/infra/deploy-vm-bastion-libvirt.yml
Labels: lgtm, approved
