Repository openshift-kni/eco-ci-cd, pull requests merged in 2025-07, with the labels that each got.

#137 Added remote_src true to the copy module, add assertion on the url file
  playbooks/cnf/upload-report.yaml
Labels: lgtm, approved

#141 Add task to copy polarion url file before deletion, adjust path in th…
  playbooks/cnf/upload-report.yaml
  scripts/send-slack-notification-bot.py
Labels: lgtm

#142 TELCOV10N-739: allow additional manifest for OCP installation
  playbooks/deploy-ocp-hybrid-multinode.yml
Labels: lgtm, approved

#145 Changed send-slack-notification script to use argparse for cross team use
  scripts/send-slack-notification-bot.py
Labels: lgtm

#148 cnf-network: update z-stream cluster mapping
  playbooks/setup-cluster-env.yml
Labels: lgtm, approved

#151 TELCOV10N-739: adding Cgroup version
  playbooks/compute/deploy-nto-gotest.yml
  playbooks/compute/nto/roles/configurecluster/handlers/main.yml
  playbooks/compute/nto/roles/configurecluster/tasks/cgroup.yml
  playbooks/compute/nto/roles/configurecluster/tasks/containerRuntime.yml
  playbooks/compute/nto/roles/configurecluster/tasks/machineConfigPool.yml
  playbooks/compute/nto/roles/configurecluster/tasks/main.yml
  playbooks/compute/nto/roles/configurecluster/templates/performanceProfile.yml.j2
Labels: lgtm, approved

#153 TELCOV10N-739: fix issue running go tests
  playbooks/compute/deploy-nto-gotest.yml
Labels: lgtm, approved

#155 deploy-run-eco-gotests: overwrite FRR image if env var is set
  playbooks/cnf/deploy-run-eco-gotests.yaml
  playbooks/cnf/templates/run_eco_gotests.j2
Labels: approved

#158 Add comprehensive Cursor rules for telco Prow step development
  .cursor/rules/prow-job-creation-guide.mdc
  .cursor/rules/telco-prow-steps.mdc
Labels: lgtm, approved

#160 cnf network: eco-gotests added performance profile name
  playbooks/cnf/deploy-run-eco-gotests.yaml
  playbooks/cnf/templates/run_eco_gotests.j2
Labels: approved

#164 Revert "TELCOV10N-749: Delete temporary qcow2 image after VM deployment"
  playbooks/infra/deploy-vm-bastion-libvirt.yml
Labels: lgtm, approved

#167 cnf network: added new cluster hlxcl7
  playbooks/setup-cluster-env.yml
Labels: lgtm, approved
